apiVersion: apps/v1
kind: Deployment
metadata:
  name: iresource-app-client
spec:
  selector:
    matchLabels:
      app: iresource-app-client
  template:
    metadata:
      labels:
        app: iresource-app-client
    spec:
      containers:
      - name: iresource-app-client
        image: quyennv0602/iresource-client:dev-1.3.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iresource-app-client
spec:
  selector:
    app: iresource-app-client
  ports:
  - port: 80  
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iresource-app-server
spec:
  selector:
    matchLabels:
      app: iresource-app-server
  template:
    metadata:
      labels:
        app: iresource-app-server
    spec:
      containers:
      - name: iresource-app-server
        image: quyennv0602/iresource-server:dev-1.0.5
        imagePullPolicy: Always
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres-postgresql:5432/postgres?currentSchema=iresource&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
          - name: SPRING_DATASOURCE_USERNAME
            value: postgres
          - name: SPRING_DATASOURCE_PASSWORD
            value: admin
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: iresource-app-server
spec:
  selector:
    app: iresource-app-server
  ports:
  - port: 8080
    targetPort: 8080



