apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-callback
spec:
  selector:
    matchLabels:
      app: server-callback
  template:
    metadata:
      labels:
        app: server-callback
    spec:
      containers:
        - name: server-callback
          image: us-central1-docker.pkg.dev/ikame-gem-ai-research/ikame/ikame-server-callback:v2.0.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: 2048Mi
              cpu: 1000m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server-callback
spec:
  selector:
    app: server-callback
  ports:
    - port: 8080
      targetPort: 8080
